### ISSUE TITLE
Update to use the latest version of @skyleague/axioms and set it as a dependency, not dev dependency

### ISSUE THREAD

**Issue by eugenpodaru** [skyleague/predicate#18]
### Description

This library uses @skyleague/axioms, while the library is set as a dev dependency.

Also, some of the primitives that the lib uses form axioms have been removed in the latest axioms version.

**Comment by pevisscher** [comment]
Fixed this in v2, let me know if it works :)

**Comment by eugenpodaru** [comment]
seems to be working! Thanks
